// Own project (guessing game) that compares user input with randomly generated number and allows users to play multiple times. Not an exercise for Lynda.com Learning Java course.
// Contains inputGuess method that saves user input, generates random number, and compares input and number.

import java.util.Random;
import java.util.Scanner;

public class Guess {
    public static void inputGuess() {
        // Constructor for user input
        Scanner guess = new Scanner(System.in);
        System.out.println("\nPick a number between 1 and 5.");
        // Stores user input as variable.
        int userInput = guess.nextInt();

        // Generates random number between 1 and 5. Stores random number as variable.
        Random rand = new Random();
        int randomNumber = rand.nextInt(5) + 1;

        // Check if user input and random number match and prints a message.
        if (userInput == randomNumber) {
            // Returns count variable from Main class.
            if (Main.count == 1) {
                System.out.println("Oh my gosh! Your number matched the number generated by The Randomizer: " + randomNumber + ". It only took you " + Main.count + " guess!");
                // Reset count to zero in case user want to continue playing.
                Main.count = 0;
            } else {
                System.out.println("Oh my gosh! Your number matched the number generated by The Randomizer: " + randomNumber + ". It only took you " + Main.count + " guesses!");
                // Reset count to zero in case user want to continue playing.
                Main.count = 0;
            }
        } else {
            System.out.println("Too bad. The Randomizer generated " + randomNumber + ".");
        }

    }
}
